#### 1. Import the numpy package under the name `np` (★☆☆)

In [1]:
import numpy as np

#### 2. Create a null vector of size 10 (★☆☆)

In [4]:
VectorNull = np.zeros(10)
print(VectorNull)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 3. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [8]:
VectorNull = np.zeros(10)
VectorNull[4] = 1
print(VectorNull)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


#### 4. Create a vector with values ranging from 10 to 49 (★☆☆)

In [10]:
v = np.arange(10,50)
print(v)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


#### 5. Reverse a vector (first element becomes last) (★☆☆)

In [11]:
v = v[::-1]
print(v)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


#### 6. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [14]:
m = np.arange(9).reshape(3,3)
print(m)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### 7. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [23]:
???

(array([0, 1, 4], dtype=int64),)


#### 8. Create a 3x3 identity matrix (★☆☆)

In [15]:
ide = np.eye(3,3)
print(ide)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### 9. Create a 3x3x3 array with random values (★☆☆)

In [27]:
from numpy import random
x = random.randint(1,1000,(3,3,3)) # start , end , (rows,columns)
print(x)

[[[687 712 255]
  [414 923 668]
  [209 410 623]]

 [[513 575 822]
  [172  28 415]
  [ 16 533 469]]

 [[160 753 765]
  [678  68 343]
  [132 399 616]]]


#### 10. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [33]:
x = random.randint(1000,size=(10,10)) # start , end , (rows,columns)
print(x,"\n",np.min(x),np.max(x))

[[347 886 843 519 121 907 739 663 585 115]
 [446 791 235 577 612  60 192 717 979  31]
 [738 504 183 100 791 267 761 571 137 333]
 [ 36 413 783 960 133 220 735 476 698   4]
 [630 448 710 916 443 206 589 906  85 488]
 [371 222 174 602 979 299 657 512 758 588]
 [417 583  36 976 827 809 414 369 341 999]
 [527 891 637 913  10 576 884 412 234  89]
 [745 744 887 827 634  16  89 728 260  58]
 [957 462 647 850 998 185 517  96 418 110]] 
 4 999


#### 11. Create a random vector of size 30 and find the mean value (★☆☆)

In [37]:
x = np.arange(30)
print(x,"\nMean value:",np.mean(x))

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29] 
Mean value: 14.5


#### 12. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [60]:
x = np.ones(9).reshape(3,3)
x[1,1]=0
print(x)

[[1. 1. 1.]
 [1. 0. 1.]
 [1. 1. 1.]]


#### 13. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [61]:
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1


False

#### 14. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

#### 15. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

#### 16. What are the result of the following expressions? (★☆☆)
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

#### 17. How to find common values between two arrays? (★☆☆)

#### 18. How to get the dates of yesterday, today and tomorrow? (★☆☆)

#### 19. How to get all the dates corresponding to the month of July 2016? (★★☆)

#### 20. Create a random vector of size 10 and sort it (★★☆)

#### 21. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

#### 22. How to convert a float (32 bits) array into an integer (32 bits) in place?

#### 23. How to read the following file? (★★☆)
```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

#### 24. Subtract the mean of each row of a matrix (★★☆)

#### 25. How to sort an array by the nth column? (★★☆)

#### 26. How to tell if a given 2D array has null columns? (★★☆)